# Site settings
title: Nick Musaelian
email: nick@nickmusaelian.com
#url: "http://www.nickmusaelian.com"
#url: "http://nickmusaelian.github.io"
url: http://localhost:4000

# Build settings
markdown: kramdown

permalink: /:title

starting_painting: forget-the-monkeys

maxheight: 900px

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: image
