# Site settings
title: Nick Musaelian
email: nick@nickmusaelian.com
#url: "http://www.nickmusaelian.com"
url: "http://nickmusaelian.github.io"

# Build settings
markdown: kramdown

permalink: /:title

starting_painting: forget-the-monkeys

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: image
